// resources and blogs rich text only



// -------
// GPDN Cloudflare Credentials

// gpdnofficial@gmail.com
// Orieal@2025!

// GPDN Twilio Credentials

// gpdnofficial@gmail.com
// Orieal@2025!


// 82.112.236.105
// root
// qVOQpbpxe90YrmAyw)1H


// gpdndev@gmail.com
// GPDN@2025!


// i take the premium version of twilio what else i need to do to send message to any whatsapp number without verifying the number


//       good ui design web
// ==============================================================================================

// https://askyoursenior.com/                                              

//                                                     Ai - application testing platform ( for testing web and app)
// ====================================================================================================

// =====teststripe



//                                          New Things
// ==========================================================================================
// superbase(database)
// --==cloudflare

// tempo , lovable ,vinsurf , v0 , databutton , tempolabs ,boltdot
// ------------------------ai for page generator--------------------

// --==trea

// --==curser



// react quill



// ----------------------------------------------vedio editing app------------------------
// --capcut
// --vneditor
// --vita
// --beatleap
// --inshot 
// pm2 restart gpdn-backend



// IP Address - 82.112.236.105
// Username - root
// Password - 3+oft,Hv(SD(&f0H#KaD
// Port - 22
//  api.thegpdn.org 

// Host - srv789806.hstgr.cloud
// Root Password - 3+oft,Hv(SD(&f0H#KaD