//            Atlas secrets
// ==================================

// Username:Muhammed Nihal

// Password:fu7OA4o6jSBdcRf8

//           AWS account name
// =================================

//  AWS account name:NihalNode-js-AWS

//   AWS account password:ufVe?!2p"H33X=A

//   security code :123



//              Domain Name 
// =====================================

//   Domain Name:CozaStore.com



//            terminal 
// ==============================
// pwd =give which folder we are located